### ISSUE TITLE
Many types missing on d.ts files

### ISSUE THREAD

**Issue by Nirco96** [TGFTech/angular-cesium#155]
Hey, after updating to 0.0.32 angular-cli throws many compilation errors, for example: 
coordinate-converter.service.d.ts: 36,9 Member 'longtitude' explicitly has an 'any' type

This error occurs many times in many different files and prevents me from starting my application... 
Thank you!

**Comment by eitanfr** [comment]
fixed on #156
